language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rtYmaCwQtGU7m6jZXJiadqthR+ONK/11T4Aq0jsbf5JjbiZ//OiclAVvcEPvWIwfu7RXgs8nTv5xQtcNlxLpTyM2Y5MKuTlG/xR7DKJ3AGXARfrRiPvTS9X0eZbQ+PQsYWW50kgW+Rjh54VH5FOyEljh4GStgG/MZHp9kWyogSNY1XR0rzSK//8BFGS5gjmnaSu1q6X6rdFMGOXYHQDP6nhu8Txeos3mo4zEp/bTUhhfuzhYwfc/m2FbzC8vUOmu87Z3GEKQ/AYUF9H+Cob0qcEtQv/uUy13bmDh0RR+OnQi5pFDH8oaG2rV7ihWkR9swsBfuE2fZ7hIO4sQB7bk5GKzJJ/EVVPuy0Qfa2Ke0+4pV0iHABM/22vdTyM2MbnsIx2jNstc6JihCnINM8Zn2yuqnkvppeETLpBSjd9nyGSan5HjC6U7BWSmXBKl8c26U2+/0rbzb0BTBMUqnfkuqTunOoY/xdxmkt08P3dkKAY6DWf+7mXUf5gkjqj1Z1zHOh4y05IQs5CyaZBMPR/UUw+6e3QzZZNcdIrt48LVeGHsuCX77+zHiAZnx7XvlTXauJ3gtac/veVZsLXyKJDlAbB4UMIwHinpTjS6rV3ult8XDYhZCy5dVnX0p8i8Eej6niLq1u58TBxvWpMz2Wf73/LbDq6/IU029tMOURtKghY=
  file:
    - 'unist-util-is.js'
    - 'unist-util-is.min.js'
  on:
    tags: true
